on: [push]
jobs:
  job_1:
    name: Create / Update Function 1 to Segment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Preparing Function
        uses: actions/checkout@v2
      - shell: bash
        run: |
          echo "Function Code Is"
          cp src/function.js lib/function.txt
          value="$(< lib/function.txt)"
          value="${value//$'Object.defineProperty(exports, \"__esModule\", { value: true });'/''}"
          value="${value//$'exports.onRequest = void 0;'/''}"
          value="${value//$'exports.onRequest = onRequest;'/''}"
          value="${value//'%'/'%25'}"
          value="${value//$'\n'/'%0A'}"
          value="${value//$'\r'/'%0D'}"
          echo $value
          echo "::set-output name=function_code::$value"
        id: checkout
      - name: Sending Function to Segment
        uses: samgehret/manageSegmentFunction@v1.6 # Uses an action in the root directory will need to be updated once this is on the Actions Marketplace.
        with:
          token: '<access_token>'
          function-code: ${{ steps.checkout.outputs.function_code }}
          function-name: '<fn_name>'
          function-type: <fn_type>
          workspaceID: <work_id>
          function-id: <fn_id>
